### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by fringillidaes** [NoPantsCrash/dump2json#1]
Hello!

Saw this tool in the discord and wanted to give it a try after a few attempts I kept getting the error,
  File "dump2json.py", line 6
    def extract(baselink: str, jsonfilename: str):
                        ^
SyntaxError: invalid syntax

I fixed this when adding content by changing it from,
indexer(baselink="https://the-eye.eu/public/rom/",jsonfilename="test")

to this,
extract(baselink="https://the-eye.eu/public/rom/",jsonfilename="test")

**Comment by NoPantsCrash** [comment]
> indexer

My bad, will change it to match the readme
